service: photomnemonic

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  stage: public
  stackName: photomnemonic-public
  timeout: 30
  usagePlan:
    quota:
      limit: 1000
      period: MONTH
    throttle:
      rateLimit: 5
      burstLimit: 10

functions:
  screenshot:
    handler: index.handler
    events:
      - http:
          method: get
          path: "screenshot/{url}"
          request:
            parameters:
              paths:
                url: true
          contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  apigwBinary:
    types:
      - '*/*'
