AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Photomnemonic
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ScreenshotApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        paths:
          "/screenshot/{url}":
            get:
              consumes:
                - "application/json"
              parameters:
                - name: url
                  in: path
                  required: true
                  type: string
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ScreenshotFunction.Arn}/invocations
              requestTemplates:
                "application/json": "{\"url\": \"$input.params('url')\"}"
          "/thumbnail/{url}":
            get:
              consumes:
                - "application/json"
              parameters:
                - name: url
                  in: path
                  required: true
                  type: string
                - name: width
                  in: query
                  required: true
                  type: number
                - name: height
                  in: query
                  required: true
                  type: number
                - name: fit
                  in: query
                  required: false
                  type: string
                - name: position
                  in: query
                  required: false
                  type: string
                - name: gravity
                  in: query
                  required: false
                  type: string
                - name: strategy
                  in: query
                  required: false
                  type: string
                - name: background
                  in: query
                  required: false
                  type: string
                - name: withoutEnlargement
                  in: query
                  required: false
                  type: boolean
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ThumbnailFunction.Arn}/invocations
              requestTemplates:
                "application/json": "{\"url\": \"$input.params('url')\"}"

  ScreenshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.screenshot
      Runtime: nodejs8.10
      Events:
        Screenshot:
          Type: Api
          Properties:
            Path: /screenshot
            Method: get
            ContentHandling: CONVERT_TO_BINARY

  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.thumbnail
      Runtime: nodejs10.x
      Events:
        Thumbnail:
          Type: Api
          Properties:
            Path: /thumbnail
            Method: get
            ContentHandling: CONVERT_TO_BINARY

Outputs:
  ScreenshotApi:
    Description: "API Gateway endpoint URL for Prod stage for Screenshot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/screenshot/"
  ScreenshotFunction:
    Description: "Screenshot Lambda Function ARN"
    Value: !GetAtt ScreenshotFunction.Arn
  ScreenshotFunctionIamRole:
    Description: "Implicit IAM Role created for Screenshot function"
    Value: !GetAtt ScreenshotFunctionRole.Arn
  ThumbnailApi:
    Description: "API Gateway endpoint URL for Prod stage for Thumbnail function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/screenshot/"
  ThumbnailFunction:
    Description: "Thumbnail Lambda Function ARN"
    Value: !GetAtt ThumbnailFunction.Arn
  ThumbnailFunctionIamRole:
    Description: "Implicit IAM Role created for Thumbnail function"
    Value: !GetAtt ThumbnailFunctionRole.Arn
