name: photomnemonic
on:
  push:
    branches:
    paths-ignore: ["README.md"]
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@feature/turkeyGitops-channelLatest
    with:
      registry: mozillareality
      # dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
